### ISSUE TITLE
Latest CiviCase (1.14.0) Breaks Activities Tab in Contact Summary

### ISSUE THREAD

**Issue by pbarmak** [compucorp/uk.co.compucorp.civicase#752]
After upgrading both CiviCase (to 1.14.0) and Core (to 5.35.1), when we go to a specific Contact record and click on Activities, nothing shows up even though there are activities. If I disable CiviCase, activities show up (in the old table listing format/style). My dev console shows the following error with CiviCase is enabled and I refresh the Activities page:

```
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.8.0/$injector/modulerr?p0=civicaseActivitiesTab&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.8.0%2F%24injector%2Fmodulerr%3Fp0%3Dcivicase%26p1%3D%255B%2524injector%253Aunpr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.8.0%252F%2524injector%252Funpr%253Fp0%253DActivityFormsProvider%250AF%252F%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A7%253A168%250Afb%252Fp.%2524injector%253C%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A46%253A468%250Ad%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fall%252Fmodules%252Fcivicrm%252Fbower_components%252Fangular%252Fangular.min.js%253Fqqsczv%253A44%253A197%250Ae%2540https%253A%252F%252Fcrm.thespectrumworks.org%252Fsites%252Fa…
    Angular 7
    jQuery 9
    refresh crm.ajax.js:303
    jQuery 8
    refresh crm.ajax.js:284
    jQuery 5
    loadPage crm.ajax.js:372
    <anonymous> TabHeader.js:52
    jQuery 38
    <anonymous> TabHeader.js:56
    jQuery 8
angular.js:99

```

**Comment by reneolivo** [comment]
Thanks @pbarmak we'll check this one. 

I don't see any errors on the console. Can you give us more steps to reproduce this one?

Also, please try to clear the CiviCRM cache if possible.

**Comment by pbarmak** [comment]
@reneolivo
Let's see if [this screenshot](https://www.dropbox.com/s/sph7a99cb8i5lij/activity.jpg?dl=0) will help. The steps are: update CiviCRM to 5.35.1, update CiviCase to latest and enable it, go to an Individual that has any Activities, click on the Activities tab and you'll see a blank screen, plus an error in the dev console.

If I comment out line 23 of civicase.php - the hook call to new CRM_Civicase_Hook_Tabset_ActivityTabModifier(), or just disable CiviCase, and then refresh the Individual contact page and click on Activities, the screen shows activities with the core/standard Civi layout (not the nice, new layout that CiviCase brings, which we love). So it's definitely something with the CiviCase code, but I'm not exactly sure what it is. I just know that commenting out the tabset hook for activities is a workaround for now.

**Comment by deb1990** [comment]
@pbarmak I have tried reproducing this, but as @reneolivo mentioned its not happening for us. 
The Activity Tab is loading fine. Could you also check if the Cases tab under the Contacts Summary is working? Also what about the Manage Cases screen? and the Activity Tab inside a Case? are they working?

I tried to go through the console message you posted, the the final error is this https://code.angularjs.org/1.8.0/docs/error/$injector/unpr?p0=ActivityFormsProvider.
Which says  `Unknown provider: ActivityFormsProvider`.
But this file clearly exists https://github.com/compucorp/uk.co.compucorp.civicase/blob/1.14.0/ang/civicase-base/providers/activity-forms.provider.js.

So you might want to check, if this code exists in your installation.

**Comment by pbarmak** [comment]
@deb1990 Shoot, I didn't even check the Cases tab on the Contact Summary. That is also not working. Same type of error. Glad you brought it up. Same workaround - if I comment out the hook, Cases show up in the old style. If I uncomment the hook, it's broken.

Manage Cases works fine. Activity tab under a case also works fine.

I do see the activity-forms.provider.js file in our git install. So I'm a little stumped.

I installed CiviCase using git (pulling from the repo). Do you all have CiviCase set to install from the Civi Extensions UI instead? I wonder if I'm not pulling everything somehow?

Or could it be that the code is there, but the hook is not calling the right js files somehow?

**Comment by reneolivo** [comment]
@pbarmak I remember a similar error happening when the files were not found by the CiviCRM assets manager. I fixed this in https://github.com/compucorp/uk.co.compucorp.civicase/pull/717 specifically where it says "Unknown path error".

Can you test something for me? 

1 - Do you get the "Unknown Path" when you navigate to civicase?

2 - can you change this file:
https://github.com/compucorp/uk.co.compucorp.civicase/pull/717/commits/deedd0cd63bfc05b79bb81201f09abfe177d002b#diff-3f1fe8dfa2418bcffdd2a81296d81a5e8a7c7748f19c99bcb11cf78b2eccb4ecR53-R58 
`CRM/Civicase/Helper/GlobRecursive.php`

The `getRelativeToPath` should be this one instead:

```php
public static function getRelativeToPath($basePath, $pattern) {
    return self::get($basePath . DIRECTORY_SEPARATOR . $pattern);
  }
```

Does it work for you now?

**Comment by james-compucorp** [comment]
@pbarmak have you tried updating to the latest version of Civi? 1.16? That should fix your problem as the latest version is compatible with Civi 5.35

**Comment by pbarmak** [comment]
@james-compucorp Unfortunately, it did not fix the issue. I'm on CiviCase 1.16.0 and Civi Core 5.36.1. Same issue, the Contact Activity and Case tabs don't work.

**Comment by james-compucorp** [comment]
@pbarmak at the moment is has been tested on v5.35.1. We have not checks against 5.36+. Could you try it with the Civi version mentioned?

**Comment by UshaMakoa** [comment]
Hi same problem here. Could we contribute to fix this problem for 5.36+ ?

**Comment by jamienovick** [comment]
@deb1990 can we review this please? @james-compucorp FYI Thanks

**Comment by deb1990** [comment]
@UshaMakoa yes sure, contributions are always welcome. Please make sure that the fix works for both 5.35 and 5.36(or later) versions. Thanks.

**Comment by olayiwola-compucorp** [comment]
The issue is now resolved in the latest version of the extension
